on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: execute script # run the run.py to get the latest data
        run: |
          python load_data_to_db.py
      - name: add to git and commit
        run: |
          git config --global user.email "jmaslek11@gmail.com"
          git config --global user.name "James"
          git add -A
          git commit
          git push
